repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        additional_dependencies: ['click>=8.0.4']
        language_version: python3.10
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      args: ["--max-line-length", "120", "--ignore", "F811,E501"]
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: make test
        language: system
        stages:
          - push
        always_run: true
        pass_filenames: false
